### ISSUE TITLE
Performance is terrible

### ISSUE THREAD

**Issue by FormalSnake** [atinylittleshell/TerminalOne#36] opened 2024-01-16 09:05 UTC
It is even slower than it is in the recording. It renders in as a 90s image on the internet. It might also be because it is an intel app on M1. Also there is a weird stretching going on. Github doesn't allow me to record the screen because of file size limits, so I will give a screenshot.
<img width="1680" alt="Screenshot 2024-01-16 at 09 04 39" src="https://github.com/atinylittleshell/TerminalOne/assets/90651091/66115b87-469c-4b50-96c8-1132779cee3f">
<img width="1680" alt="Screenshot 2024-01-16 at 09 04 46" src="https://github.com/atinylittleshell/TerminalOne/assets/90651091/b5b7a576-96bb-4f6d-ad02-3130fc4378b1">
Startup time is also extremely slow.

**Comment by FormalSnake** [comment] 2024-01-16 09:22
my config btw
```ts
// see https://github.com/atinylittleshell/TerminalOne/blob/main/packages/types/defaultConfig.ts for supported configuration values
module.exports = {
  acrylic: true,
  fontFamily: '"CommitMono Nerd Font", monospace',
};

```

**Comment by atinylittleshell** [comment] 2024-01-16 09:25
Thanks for the info. Something must be off there.. will take a look when I get a chance. 

I believe stretching may be a different letter spacing value, which can be configured.

**Comment by sboesebeck** [comment] 2024-01-16 14:05
I tried DOOM-Fire (zig) and I get about 100fps with TerminalOne but 300 with Wezterm.

**Comment by atinylittleshell** [comment] 2024-01-16 16:38
Good info! This + acrylic setting not working for you @sboesebeck makes me think the app is not getting GPU-acceleration. Any chance hardware acceleration got disabled for your chromium? Can you paste your chrome://gpu?

**Comment by atinylittleshell** [comment] 2024-01-16 16:55
Also any chance you are affected by Mac's energy saver disabling hardware graphics? 

![image](https://github.com/atinylittleshell/TerminalOne/assets/3233006/3ed9ff67-f237-48fd-8e5b-5016fd456b89)

**Comment by FormalSnake** [comment] 2024-01-16 17:18
An M1 build would help significantly.
I used to have my own electron terminal and the performance is much better on M1 builds.

**Comment by atinylittleshell** [comment] 2024-01-16 17:20
@FormalSnake makes sense. Will look into it!

**Comment by atinylittleshell** [comment] 2024-01-17 06:35
check this out - https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.4.0 

we now release an arm64 build which might solve the problem here - let me know how it goes?

**Comment by FormalSnake** [comment] 2024-01-17 07:38
I will check it out

**Comment by FormalSnake** [comment] 2024-01-17 07:42
is damaged and can’t be opened. You should move it to the Trash

**Comment by FormalSnake** [comment] 2024-01-17 07:44
fixed it with: xattr -cr /path/to/application.app
startup time was good though
![Screenshot 2024-01-17 at 07 44 02](https://github.com/atinylittleshell/TerminalOne/assets/90651091/b077b730-232d-44a5-9c82-a34ed599ea77)

**Comment by atinylittleshell** [comment] 2024-01-17 07:54
Thanks! I know what's wrong with node-pty there.. needs a bit of work. 

I'll try to get an Apple silicon so I can repro and better verify my fixes..

**Comment by FormalSnake** [comment] 2024-01-17 08:57
Thanks

**Comment by FormalSnake** [comment] 2024-01-17 09:04
My terminal works with M1, but it is highly outdated. It might help though.
https://github.com/FormalSnake/Formalterm

**Comment by atinylittleshell** [comment] 2024-01-17 09:40
I learned that m1 apps all need to be codesigned - https://github.com/electron-userland/electron-builder/issues/5850.

I'm not doing codesigning at the moment so likely that's the cause. @FormalSnake when you made your terminal work on m1, did you have to codesign?

**Comment by FormalSnake** [comment] 2024-01-17 09:56
I did not, probably because I am on an M1 mac. That is an annoying issue.

**Comment by atinylittleshell** [comment] 2024-02-17 07:26
@FormalSnake I've codesigned the app... now the arm64 build might be finally working. Do you mind testing on your end? https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.6.1

**Comment by FormalSnake** [comment] 2024-02-17 09:00
Sure!

**Comment by FormalSnake** [comment] 2024-02-17 09:02
The PTY still doesn't work but the terminal starts up very quickly.
<img width="1680" alt="Screenshot 2024-02-17 at 11 01 48" src="https://github.com/atinylittleshell/TerminalOne/assets/90651091/c90dba66-24f9-471b-8a84-c0760ce50eb9">

**Comment by atinylittleshell** [comment] 2024-02-17 09:12
Thank you! I'll take another look at the problem with pty.

**Comment by atinylittleshell** [comment] 2024-02-19 09:03
@FormalSnake finally - I think this build works https://github.com/atinylittleshell/TerminalOne/releases/tag/v1.6.3. I tested it on a M2 macbook and it's good. Let me know how it works for you?

**Comment by FormalSnake** [comment] 2024-02-19 11:20
It works very nicely, the only thing I miss now is the design itself.
The terminal cursor seems to flicker though.

**Comment by atinylittleshell** [comment] 2024-02-19 23:25
@FormalSnake awesome - I'll close this issue now. I'm working on a small rewrite for the frontend which will further improve performance and also address the design. 

For cursor flicker, if you have a chance do you mind filing another issue with details?

**Closed by atinylittleshell** 2024-02-19 23:25 UTC
